# Generated by Django 4.0.4 on 2022-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='flower_type',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
