# Generated by Django 4.0.4 on 2022-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_deal_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='total_check',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
